#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - run: ci/install-bazel.sh
      - run: ci/install-bazel-rbe-credential.sh
      - run: ci/run-bazel.sh bazel build //...

  dependency-update:
    machine: true
    steps:
      - checkout
      - run: ci/install-bazel.sh
      - run:
          name: Sync grakn:master graql:master client-java:master client-python:master client-nodejs:master docs:master and examples:master with the latest build-tools:master
          command: |
            ci/run-bazel.sh bazel run //release:dependency-update -- --dependency build-tools:master \
              --user grakn:master graql:mster client-java:mster client-python:master client-nodejs:master docs:master examples:master

workflows:
  build-tools:
    jobs:
      - build
#      - dependency-update