#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run: bash ./tool/bazelinstall/linux.sh
      - run: bash ./tool/bazelinstall/rbe.sh
  
  run-bazel:
    parameters:
      command:
          type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run-bazel:
          command: bazel build //...

  deploy-apt-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: |
          export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //distribution/apt:deploy-apt -- snapshot

  deploy-rpm-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: sudo apt-get update && sudo apt-get install rpm
      - run: |
          export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //distribution/rpm:deploy-rpm -- snapshot

  sync-dependencies-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //tool/sync:dependencies -- \
          --source dependencies@$CIRCLE_SHA1 \
          --targets \
          common:master protocol:master graql:master grakn:master grakn-kgms:master \
          client-java:master client-python:master client-nodejs:master \
          console:master workbase:master biograkn:master \
          docs:master examples:master kglib:master

  release-approval:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-bazel
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //tool/release:approval

  deploy-github:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //tool/release:create-notes -- dependencies $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $CIRCLE_SHA1
  
  deploy-apt:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: cat VERSION
      - run: |
          export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //distribution/apt:deploy-apt -- release

  deploy-rpm:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: sudo apt-get update && sudo apt-get install rpm
      - run: |
          export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //distribution/rpm:deploy-rpm -- release

  sync-dependencies-release:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/dependencies
    steps:
      - checkout
      - install-bazel
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run //tool/sync:dependencies -- \
          --source dependencies@$CIRCLE_SHA1 \
          --targets \
          common:master protocol:master graql:master grakn:master grakn-kgms:master \
          client-java:master client-python:master client-nodejs:master \
          console:master workbase:master biograkn:master \
          docs:master examples:master kglib:master

  release-cleanup:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git push --delete https://$REPO_GITHUB_TOKEN@github.com/graknlabs/dependencies dependencies-release-branch

workflows:
  dependencies:
    jobs:
      - build
      - deploy-apt-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy-rpm-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
      - sync-dependencies-snapshot:
          filters:
            branches:
              only: master
          requires:
            - deploy-apt-snapshot
            - deploy-rpm-snapshot
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - sync-dependencies-snapshot
  dependencies-release:
    jobs:
      - deploy-github:
          filters:
            branches:
              only: dependencies-release-branch
      - deploy-approval:
          type: approval
          requires:
            - deploy-github
          filters:
            branches:
              only: dependencies-release-branch
      - deploy-apt:
          filters:
            branches:
              only: dependencies-release-branch
          requires:
            - deploy-approval
      - deploy-rpm:
          filters:
            branches:
              only: dependencies-release-branch
          requires:
            - deploy-approval
      - sync-dependencies-release:
          filters:
            branches:
              only: dependencies-release-branch
          requires:
            - deploy-apt
            - deploy-rpm
      - release-cleanup:
          filters:
            branches:
              only: dependencies-release-branch
          requires:
            - sync-dependencies-release
